eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: clientName
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aaa081215/cloudconfig.git
          username: 1203269511@qq.com
          password: Aaa081215.

